config/routes.rb
Headhunt::Application.routes.draw do
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  devise_for :candidates, :controllers => {:registrations => "candidates/registrations"}

  resources :jobs

  resources :salaries

  resources :salary_types

  resources :job_types

  resources :clients

  resources :companies

  resources :positions

  delete "candidate_jobs", to: "candidate_jobs#destroy"
  post "candidate_jobs", to: "candidate_jobs#new"

  delete "apply", to: "apply#destroy"
  post "apply", to: "apply#apply"
  get "remove", to: "apply#remove"

  get "service_level/levels"
  post "service_level/select"

  get "site/recruiter", as: 'client_root'
  get "site/recruiter_job_management"
  get "site/applications_manager"

  get "site/candidate", as: 'candidate_root'

  get "site/login"

  get "site/contact"
  get "site/about"
  get "site/candidate_search"

  get "site/main"
  root to: "site#main"

  resources :user_types  
  
  resources :subcategories

  resources :categories

  resources :candidates do
    collection do
      patch 'add_cv'
      delete 'destroy_cv'
    end
  end

  resources :skills
  

end

app/models/apply.rb
class Apply < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :job
  has_one :client, :through => :job
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :knowledges
has_many :skills, :through => :knowledges
has_many :applies
has_many :candidate_jobs
has_many :jobs, :through => :applies
has_attached_file :cv 

validates_attachment :cv, :content_type => { :content_type => ['application/txt', 'text/plain',
'application/pdf', 'application/msword',
'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
'application/vnd.oasis.opendocument.text',
'application/x-vnd.oasis.opendocument.text',
'application/rtf', 'application/x-rtf', 'text/rtf', 
'text/richtext', 'application/doc', 'application/docx', 'application/x-soffice', 'application/octet-stream'] }

end

app/models/candidate_job.rb
class CandidateJob < ActiveRecord::Base
	has_one :candidate
	has_one :job
    validates :candidate_id, presence: true 
    validates :job_id, presence: true 
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :subcategories
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :position
  has_one :company
  belongs_to :service_level
  has_many :jobs
  has_many :applies, :through => :jobs
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_one :client, dependent: :nullify
  has_attached_file :logo
  validates_attachment :logo , :content_type => {:content_type => ['image/jpeg']}
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
belongs_to :client
belongs_to :subcategory
belongs_to :salary
belongs_to :job_type
belongs_to :country
has_one :company, through: :client
has_many :candidate_jobs
has_many :applies
validates :job_title, presence: true
validates :job_type_id, presence: true
validates :country_id, presence: true
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
has_many :jobs
end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
belongs_to :candidate
belongs_to :skill
end

app/models/position.rb
class Position < ActiveRecord::Base
has_many :clients
end

app/models/salary.rb
class Salary < ActiveRecord::Base
belongs_to :salary_type
has_many :jobs
end

app/models/salary_type.rb
class SalaryType < ActiveRecord::Base
has_many :salaries
end

app/models/service_level.rb
class ServiceLevel < ActiveRecord::Base
  has_many :clients
end

app/models/skill.rb
class Skill < ActiveRecord::Base
has_many :knowledges
has_many :candidates, :through => :knowledges

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
belongs_to :category
has_many :jobs
end

app/controllers/salary_types_controller.rb
class SalaryTypesController < ApplicationController
  before_action :set_salary_type, only: [:show, :edit, :update, :destroy]

  # GET /salary_types
  # GET /salary_types.json
  def index
    @salary_types = SalaryType.all
  end

  # GET /salary_types/1
  # GET /salary_types/1.json
  def show
  end

  # GET /salary_types/new
  def new
    @salary_type = SalaryType.new
  end

  # GET /salary_types/1/edit
  def edit
  end

  # POST /salary_types
  # POST /salary_types.json
  def create
    @salary_type = SalaryType.new(salary_type_params)

    respond_to do |format|
      if @salary_type.save
        format.html { redirect_to @salary_type, notice: 'Salary type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @salary_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @salary_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salary_types/1
  # PATCH/PUT /salary_types/1.json
  def update
    respond_to do |format|
      if @salary_type.update(salary_type_params)
        format.html { redirect_to @salary_type, notice: 'Salary type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @salary_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_types/1
  # DELETE /salary_types/1.json
  def destroy
    @salary_type.destroy
    respond_to do |format|
      format.html { redirect_to salary_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary_type
      @salary_type = SalaryType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_type_params
      params.require(:salary_type).permit(:name, :description, :currency)
    end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def format_location(j)
    if j.location == '' 
      return j.country.name 
    else 
      return j.location+', '+j.country.name 
    end 
  end  
end

app/helpers/salary_types_helper.rb
module SalaryTypesHelper
end

app/helpers/site_helper.rb
module SiteHelper

#Returns a string of the number of applies for a job that do not have a value for reject. If there are no values the string is empty.
  def newApplies (j)
    newApplies = j.applies.where({reject: nil}).length
    if newApplies == 0 then return '' else return '('+newApplies.to_s+')' end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/salary_types/_form.html.erb
<%= form_for(@salary_type) do |f| %>
  <% if @salary_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary_type.errors.count, "error") %> prohibited this salary_type from being saved:</h2>

      <ul>
      <% @salary_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salary_types/edit.html.erb
<h1>Editing salary_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @salary_type %> |
<%= link_to 'Back', salary_types_path %>

app/views/salary_types/index.html.erb
<h1>Listing salary_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Currency</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @salary_types.each do |salary_type| %>
      <tr>
        <td><%= salary_type.name %></td>
        <td><%= salary_type.description %></td>
        <td><%= salary_type.currency %></td>
        <td><%= link_to 'Show', salary_type %></td>
        <td><%= link_to 'Edit', edit_salary_type_path(salary_type) %></td>
        <td><%= link_to 'Destroy', salary_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary type', new_salary_type_path %>

app/views/salary_types/new.html.erb
<h1>New salary_type</h1>

<%= render 'form' %>

<%= link_to 'Back', salary_types_path %>

app/views/salary_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salary_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @salary_type.description %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @salary_type.currency %>
</p>

<%= link_to 'Edit', edit_salary_type_path(@salary_type) %> |
<%= link_to 'Back', salary_types_path %>