config/routes.rb
Headhunt::Application.routes.draw do
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  devise_for :candidates, :controllers => {:registrations => "candidates/registrations"}

  resources :jobs

  resources :salaries

  resources :salary_types

  resources :job_types

  resources :clients

  resources :companies

  resources :positions

  delete "candidate_jobs", to: "candidate_jobs#destroy"
  post "candidate_jobs", to: "candidate_jobs#new"

  delete "apply", to: "apply#destroy"
  post "apply", to: "apply#apply"
  get "remove", to: "apply#remove"

  get "service_level/levels"
  post "service_level/select"

  get "site/recruiter", as: 'client_root'
  get "site/recruiter_job_management"
  get "site/applications_manager"

  get "site/candidate", as: 'candidate_root'

  get "site/login"

  get "site/contact"
  get "site/about"
  get "site/candidate_search"

  get "site/main"
  root to: "site#main"

  resources :user_types  
  
  resources :subcategories

  resources :categories

  resources :candidates do
    collection do
      patch 'add_cv'
      delete 'destroy_cv'
    end
  end

  resources :skills
  

end

app/models/apply.rb
class Apply < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :job
  has_one :client, :through => :job
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :knowledges
has_many :skills, :through => :knowledges
has_many :applies
has_many :candidate_jobs
has_many :jobs, :through => :applies
has_attached_file :cv 

validates_attachment :cv, :content_type => { :content_type => ['application/txt', 'text/plain',
'application/pdf', 'application/msword',
'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
'application/vnd.oasis.opendocument.text',
'application/x-vnd.oasis.opendocument.text',
'application/rtf', 'application/x-rtf', 'text/rtf', 
'text/richtext', 'application/doc', 'application/docx', 'application/x-soffice', 'application/octet-stream'] }

end

app/models/candidate_job.rb
class CandidateJob < ActiveRecord::Base
	has_one :candidate
	has_one :job
    validates :candidate_id, presence: true 
    validates :job_id, presence: true 
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :subcategories
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :position
  has_one :company
  belongs_to :service_level
  has_many :jobs
  has_many :applies, :through => :jobs
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_one :client, dependent: :nullify
  has_attached_file :logo
  validates_attachment :logo , :content_type => {:content_type => ['image/jpeg']}
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
belongs_to :client
belongs_to :subcategory
belongs_to :salary
belongs_to :job_type
belongs_to :country
has_one :company, through: :client
has_many :candidate_jobs
has_many :applies
validates :job_title, presence: true
validates :job_type_id, presence: true
validates :country_id, presence: true
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
has_many :jobs
end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
belongs_to :candidate
belongs_to :skill
end

app/models/position.rb
class Position < ActiveRecord::Base
has_many :clients
end

app/models/salary.rb
class Salary < ActiveRecord::Base
belongs_to :salary_type
has_many :jobs
end

app/models/salary_type.rb
class SalaryType < ActiveRecord::Base
has_many :salaries
end

app/models/service_level.rb
class ServiceLevel < ActiveRecord::Base
  has_many :clients
end

app/models/skill.rb
class Skill < ActiveRecord::Base
has_many :knowledges
has_many :candidates, :through => :knowledges

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
belongs_to :category
has_many :jobs
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(salary_params)

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @salary }
      else
        format.html { render action: 'new' }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:min, :max, :salary_type_id)
    end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def format_location(j)
    if j.location == '' 
      return j.country.name 
    else 
      return j.location+', '+j.country.name 
    end 
  end  
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/site_helper.rb
module SiteHelper

#Returns a string of the number of applies for a job that do not have a value for reject. If there are no values the string is empty.
  def newApplies (j)
    newApplies = j.applies.where({reject: nil}).length
    if newApplies == 0 then return '' else return '('+newApplies.to_s+')' end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/salaries/_form.html.erb
<%= form_for(@salary) do |f| %>
  <% if @salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% @salary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :min %><br>
    <%= f.text_field :min %>
  </div>
  <div class="field">
    <%= f.label :max %><br>
    <%= f.text_field :max %>
  </div>
  <div class="field">
    <%= f.label :salary_type_id %><br>
    <%= f.number_field :salary_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing salary</h1>

<%= render 'form' %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>

app/views/salaries/index.html.erb
<h1>Listing salaries</h1>

<table>
  <thead>
    <tr>
      <th>Min</th>
      <th>Max</th>
      <th>Salary type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.min %></td>
        <td><%= salary.max %></td>
        <td><%= salary.salary_type_id %></td>
        <td><%= link_to 'Show', salary %></td>
        <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary', new_salary_path %>

app/views/salaries/new.html.erb
<h1>New salary</h1>

<%= render 'form' %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Min:</strong>
  <%= @salary.min %>
</p>

<p>
  <strong>Max:</strong>
  <%= @salary.max %>
</p>

<p>
  <strong>Salary type:</strong>
  <%= @salary.salary_type_id %>
</p>

<%= link_to 'Edit', edit_salary_path(@salary) %> |
<%= link_to 'Back', salaries_path %>