config/routes.rb
Headhunt::Application.routes.draw do
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  devise_for :candidates, :controllers => {:registrations => "candidates/registrations"}

  resources :jobs

  resources :salaries

  resources :salary_types

  resources :job_types

  resources :clients

  resources :companies

  resources :positions

  delete "candidate_jobs", to: "candidate_jobs#destroy"
  post "candidate_jobs", to: "candidate_jobs#new"

  delete "apply", to: "apply#destroy"
  post "apply", to: "apply#apply"
  get "remove", to: "apply#remove"

  get "service_level/levels"
  post "service_level/select"

  get "site/recruiter", as: 'client_root'
  get "site/recruiter_job_management"
  get "site/applications_manager"

  get "site/candidate", as: 'candidate_root'

  get "site/login"

  get "site/contact"
  get "site/about"
  get "site/candidate_search"

  get "site/main"
  root to: "site#main"

  resources :user_types  
  
  resources :subcategories

  resources :categories

  resources :candidates do
    collection do
      patch 'add_cv'
      delete 'destroy_cv'
    end
  end

  resources :skills
  

end

app/models/apply.rb
class Apply < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :job
  has_one :client, :through => :job
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :knowledges
has_many :skills, :through => :knowledges
has_many :applies
has_many :candidate_jobs
has_many :jobs, :through => :applies
has_attached_file :cv 

validates_attachment :cv, :content_type => { :content_type => ['application/txt', 'text/plain',
'application/pdf', 'application/msword',
'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
'application/vnd.oasis.opendocument.text',
'application/x-vnd.oasis.opendocument.text',
'application/rtf', 'application/x-rtf', 'text/rtf', 
'text/richtext', 'application/doc', 'application/docx', 'application/x-soffice', 'application/octet-stream'] }

end

app/models/candidate_job.rb
class CandidateJob < ActiveRecord::Base
	has_one :candidate
	has_one :job
    validates :candidate_id, presence: true 
    validates :job_id, presence: true 
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :subcategories
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :position
  has_one :company
  belongs_to :service_level
  has_many :jobs
  has_many :applies, :through => :jobs
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_one :client, dependent: :nullify
  has_attached_file :logo
  validates_attachment :logo , :content_type => {:content_type => ['image/jpeg']}
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
belongs_to :client
belongs_to :subcategory
belongs_to :salary
belongs_to :job_type
belongs_to :country
has_one :company, through: :client
has_many :candidate_jobs
has_many :applies
validates :job_title, presence: true
validates :job_type_id, presence: true
validates :country_id, presence: true
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
has_many :jobs
end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
belongs_to :candidate
belongs_to :skill
end

app/models/position.rb
class Position < ActiveRecord::Base
has_many :clients
end

app/models/salary.rb
class Salary < ActiveRecord::Base
belongs_to :salary_type
has_many :jobs
end

app/models/salary_type.rb
class SalaryType < ActiveRecord::Base
has_many :salaries
end

app/models/service_level.rb
class ServiceLevel < ActiveRecord::Base
  has_many :clients
end

app/models/skill.rb
class Skill < ActiveRecord::Base
has_many :knowledges
has_many :candidates, :through => :knowledges

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
belongs_to :category
has_many :jobs
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def main
	@search = Job.search(params[:q])
  end


  def contact
  end


  def about
  end


  def cv
  end
  
  
  def recruiter
    redirect_to 'site/login' unless client_signed_in?
    if current_client.service_level.nil?
      @moreJobs = false
    else
      @moreJobs = current_client.service_level.job_limit > current_client.jobs.length
    end
    @example = current_client
    @jobs = Job.where({:client_id => current_client.id})
    @recentPosts = Job.where({client_id: current_client.id}).order(created_at: :desc).take(3)
    @serviceName = current_client.service_level.nil? ? "Free" : current_client.service_level.name
    @company = Company.find(current_client.company_id) unless current_client.company_id == nil
  end
  
  
  def recruiter_job_management
    @jobs = Job.where({:client_id => current_client.id})
  end

  def applications_manager
    @jobs = Job.where({:client_id => current_client.id})
  end
  
  def reg
    @client = Client.new
  end
  
  def candidate
    if candidate_signed_in?
      @saved = CandidateJob.where({candidate_id: current_candidate.id}).pluck(:job_id)
      @saved = Job.find(@saved)
      @applications = Apply.where({candidate_id: current_candidate.id, active: true})
    else
      redirect_to('/site/login')
    end
  end
  
  def candidate_search
    @search = Candidate.search(params[:q])
    @candidates = @search.result
  end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def format_location(j)
    if j.location == '' 
      return j.country.name 
    else 
      return j.location+', '+j.country.name 
    end 
  end  
end

app/helpers/site_helper.rb
module SiteHelper

#Returns a string of the number of applies for a job that do not have a value for reject. If there are no values the string is empty.
  def newApplies (j)
    newApplies = j.applies.where({reject: nil}).length
    if newApplies == 0 then return '' else return '('+newApplies.to_s+')' end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/applications_manager.html.erb
<script type='text/javascript'>
  function hide_table(id){
    var title = $('#applications-job-title-'+id);
    title.toggleClass('job-title-application').toggleClass('job-title-application-open');
    var block = $('#table-container-'+id);
    block.css('display', (block.css('display') == 'none' ?'block':'none'));
  }
</script>
<div class='row top-margin'>
  <div id='application-titles-container' class= 'bg-info col-lg-4'>
    <h3>Application Manager</h3>
    <% @jobs.each do |j| %>
      <div id='applications-job-title-<%=j.id%>' class='job-title-application bg-info' onclick='hide_table(<%=j.id%>)' ><h4><%= j.job_title %> - <%= format_location(j) %></h4></div>
      <div id='table-container-<%=j.id%>' class='application-table-container' style='display:none;'>
        <% if j.applies.exists? %>
          <table>
            <thead>
              <th>Name</th>
              <th>E-Mail</th>
              <th>CV</th>
            </thead>
            <% j.applies.each do |a| %>
              <% candidate = a.candidate %>
              <tr>
              <td><%=link_to candidate.first_name+' '+candidate.last_name, candidate%></td>
              <td><%=candidate.email%></td>
              <% if candidate.cv.exists? %>
                <td><%=link_to candidate.cv_file_name, candidate.cv.url%></td>
              <% else %>
                <td><strong>No CV</strong>
              <% end %>
              </tr>
            <% end %>
          </table>
        <% else %>
          <strong>There are no applications</strong>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% @jobs.each do |j| %>
  <h3><%=j.job_title%></h3>
  <table class='table table-condensed'>
    <thead>
    <th>Name</th>
    <th>E-Mail</th>
    <th>CV</th>
    </thead>
    <tbody>
      <% j.applies.each do |a| %>
      <% candidate = a.candidate %>
        <tr>
          <td><%=link_to candidate.first_name+' '+candidate.last_name, candidate%></td>
          <td><%=candidate.email%></td>
          <td><%=link_to candidate.cv_file_name, candidate.cv.url%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'back', client_root_path %>

app/views/site/candidate.html.erb
<div class='row top-margin'>
  <div class='col-lg-8'>
    <h3>Candidate Profile Page</h3>
    
    You Are Logined As: 
    <strong><i><%= current_candidate.first_name%> <%= current_candidate.last_name%></i></strong>
    
    <div id='saved-jobs-container'>
      <h3>Your saved jobs</h3>
      <% @saved.each do |j| %>
        <p>
          <%= link_to j.job_title, j %> 
        </p>
      <% end %>
      <h3>Applications</h3>
      <% @applications.each do |a| %>
        <p>
          <%= link_to a.job.job_title+' @ '+a.client.company.name, a.job %>
        </p>
      <% end %>
    </div>
  </div>
  <div class='col-lg-4'>
    <div class='well' id='cv-container'>
      <h3>Your CV</h3>
      <% if current_candidate.cv.exists? %>
        <%= link_to current_candidate.cv_file_name, current_candidate.cv.url %> 
        <%= link_to 'remove', destroy_cv_candidates_path, method: :delete%>
      <% else %>
        <%= form_for @current_candidate, :url => add_cv_candidates_path, :html => { :multipart => true } do |form| %>
          <%= form.file_field :cv , :onchange => 'form.submit()' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/site/candidate_search.html.erb
<h4>Candidate Searching</h4>

<!--
<form class="form-inline" role="form">
  <div class="">
    <label class="sr-only" ></label>
    <input type="text" class="form-control" name= "skill_input" placeholder="Keywords">
  
    <label class="sr-only" ></label>
    <input type="text" class="form-control" name="work_input" placeholder="Work Backgournd">

   <label class="sr-only"></label>
   <input type="text" class="form-control" id="education_input" placeholder="Education Backgournd">
   </div>
	 <br>
   <center><button type="submit" class="btn btn-primary">Search</button></center>

</form>
-->

<div class="row">
	<div class="col-md-8">
		<form class="form-inline">
			<table>
				<tr>
					<%= search_form_for @search do |f| %>
					
					<td><%= f.text_field :candidate_skills_cont, :placeholder => "Skills"%></td>
				<td><%= f.text_field :first_name_cont, :placeholder => "Work Experience"%></td>
				<td><%= f.text_field :last_name_cont, :placeholder => "Education"%></td>
					
					<td><button 'f', class = 'btn btn-success'>Search</button> </td>
					<%end%>
				</tr>	
			</table>
		</form>       
	</div>      
</div>
    
		<h4>candidates list:</h4>

		<table class="table table-hover">
		  <thead>
		    <tr>
					
		      <th>Name</th>
					<th>skills</th>
		      <th>Phone</th>
		      <th>Location</th>	
		      <th></th>
		      <th></th>
		      <th></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @candidates.each do |candidate| %>
		      <tr>
						
		        <td><%= link_to (candidate.first_name+" " +candidate.last_name), candidate_path(candidate) %></td>
						<td><%= candidate.candidate_skills%></td>
						
		        <td><%= candidate.phone %></td>
		        <td><%= candidate.location %></td>
		       
						
		      </tr>
		    <% end %>
		  </tbody>
		</table>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2382.46522193287!2d-6.263051900000001!3d53.33492790000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48670e9f84351327%3A0xee7d84dd85a64302!2s68+Harcourt+St!5e0!3m2!1sen!2sie!4v1397561916913" width="600" height="450" frameborder="0" style="border:0"></iframe>

app/views/site/login.html.erb
<div class='row'>
  <span class='col-lg-6'>
    <h2>Candidate Log In</h2>
    <%= form_for(:candidate, :url => session_path(:candidate)) do |f| %>
      <%= f.text_field :email %>
      <%= f.password_field :password %>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
      <%= f.submit 'Sign in' %>
      <%= link_to "Forgot your password?", new_password_path(:candidate) %>
    <% end %>
    <%= link_to 'Register', new_candidate_registration_path %>
  </span>
  <span class='col-lg-6'>
    <h2>Recruiter Log In</h2>
    <%= form_for(:client, :url => session_path(:client)) do |f| %>
      <%= f.text_field :email %>
      <%= f.password_field :password %>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
      <%= f.submit 'Sign in' %>
      <%= link_to "Forgot your password?", new_password_path(:client) %>
    <% end %>
    <%= link_to 'Register', new_client_registration_path %>
  </span>
</div>

app/views/site/main.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<div class='row'>
    <h1>Are you ready for the hunt</h1>
	<div class='col-lg-6'>
		<%= image_tag('blue_target.jpg', :size => "380", class: 'main-logo') %>
	</div>
	<div class='col-lg-6' style='padding-top:70px;' >
		<%= render 'layouts/search_bar_v' %>
	</div>
</div>

app/views/site/recruiter.html.erb
<h3>Recruiter Portal Page</h3>
<div class='row margin-top'>
  <div class='col-lg-8'>
    <p>
    You Are Logined As: 
    <strong><i><%= current_client.last_name%> <%= current_client.first_name%></i></strong><br/>
    Membership level is <strong><i><%=@serviceName%></i></strong>
    </p>
    <div class='well'>
      <h4>Your Company Page</h4>
      <% if current_client.company_id.nil? %>
        <%= link_to 'Create your company page here', new_company_path %>
      <% else %>
        <strong><%=current_client.company.name%></strong>
        <%= image_tag current_client.company.logo, style: 'width:50px;' %>
        <%= link_to 'view', current_client.company %>
        <%= link_to 'edit', edit_company_path(current_client.company_id) %>
      <% end %>
    </div>
    <div id='application-titles-container' class= 'well'>
      <h3>Applications</h3>
      <% @jobs.each do |j| %>
        <div id='applications-job-title-<%=j.id%>' class='job-title-application bg-info' onclick='hide_table(<%=j.id%>)' ><h4><%= j.job_title %> - <%= format_location(j) %> <%=newApplies(j)%></h4></div>
        <div id='table-container-<%=j.id%>' class='application-table-container' style='display:none;'>
          <% if j.applies.exists? %>
            <table>
              <thead>
                <th>Name</th>
                <th>E-Mail</th>
                <th>CV</th>
              </thead>
              <% j.applies.each do |a| %>
                <% candidate = a.candidate %>
                <tr class=<%= a.reject.nil? ? 'new-applicant':''%> >
                  <td><%=link_to candidate.first_name+' '+candidate.last_name, candidate%></td>
                  <td><%=candidate.email%></td>
                  <% if candidate.cv.exists? %>
                    <td><%=link_to candidate.cv_file_name, candidate.cv.url%></td>
                  <% else %>
                    <td><strong>No CV</strong>
                  <% end %>
                </tr>
              <% end %>
            </table>
          <% else %>
            <strong>There are no applications</strong>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='col-lg-4'>
    <div class='well'>
      <% if @moreJobs %>
        <strong><i><%= link_to 'New Job', new_job_path %></i></strong>
      <% else %>
        <strong><i>You cannot post more jobs</i></strong>
      <% end %>
    </div>
    <div class='well actions-well'>
      <h4>Your Recent Job Posts</h4>
      <% @recentPosts.each do |post| %>
        <%= button_to post.job_title, post, class: 'btn btn-info', method: :get%>
      <% end %>
      <strong><%= link_to 'Mange All Jobs',site_recruiter_job_management_path %></strong>
    </div>
  </div>
</div>
<div class='row'>
  <div style='padding-top:20px;'>
    <%= link_to 'Candidates Search', site_candidate_search_path %></br>
    <%= link_to 'Select Level', service_level_levels_path %>
  </div>
</div>

app/views/site/recruiter_job_management.html.erb
<h4>This Is Job Management Page</h4>

<strong><i><%= link_to "go back", client_root_path%></i></strong>
<%# = @example.id%>

<br/><br/><br/><br/><br/><br/>
<h4>Listing Jobs:</h4>
<table class='table table-hover'>
  <thead>
    <tr>
      <th>Job title</th>
      <th>Salary</th>
      <th>Location</th>
  <!--    <th>Job type</th>
      <th>Job subcategory</th>
      <th>Client</th>--> 
      <th>Start date</th>
      <th>Expire date</th>
      <th>Content</th>
 <!--     <th>Education level</th>
      <th>Career level</th>
      <th>Contact details</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.sort_by(&:created_at).reverse.each do |job| %>
      <tr id='job-row-<%= job.id %>'>
        <td><%= job.job_title %></td>
        <td><%= job.salary_id %></td>
        <td><%= format_location(job) %></td>
    <!--     <td><%= job.job_type_id %></td>
        <td><%= job.subcategory_id %></td>
        <td><%= job.client_id %></td>-->
        <td><%= job.start_date %></td>
        <td><%= job.expire_date %></td>
        <td><%= job.content %></td>
  <!--      <td><%= job.education_level_id %></td>
        <td><%= job.career_level_id %></td>
        <td><%= job.contact_details %></td>-->
		    <td><%= link_to t('.show', :default => t("helpers.links.show")),
		               job_path(job), :class => 'btn btn-success'  %></td>
		    <td><%= link_to t('.edit', :default => t("helpers.links.edit")),
		               edit_job_path(job), :class => 'btn' %></td>
		    <td><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		               job_path(job),
                       :remote => true, 
		               :method => 'delete',
		               :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		               :class => 'btn btn-warning' %></td>
								
      </tr>		
    <% end %>
  </tbody>
</table>